#! /bin/bash

#SBATCH --job-name=diim_maps_1
#SBATCH --nodes=5
#SBATCH --ntasks-per-node=34
#SBATCH --time=2:00:00
#SBATCH --account=OGS23_PRACE_IT
#SBATCH --partition=g100_usr_prod

module load gcc/10.2.0
module load python/3.8.6--gcc--10.2.0
module load netcdf-fortran/4.5.3--openmpi--4.1.1--gcc--10.2.0
module load cmake/3.21.4
module load openblas/0.3.18--gcc--10.2.0
module load grads
module load nco/5.0.1--openmpi--4.1.1--gcc--10.2.0

export DIIM_PATH=/g100_work/OGS23_PRACE_IT/csoto/DIIM
export DIIM_ENV_PATH=/g100_work/OGS23_PRACE_IT/csoto/DIIM

date

#export RANKS_PER_NODE=1
echo "printing node list, runing: $scontrol show hostnames $SLURM_NODELIST"
scontrol show hostnames $SLURM_NODELIST
echo "Checking libxml2 before mpirun, runing: ls -l /g100_work/.../libxml2.so.2 \ md5sum /g100_work/.../libstdc++.so.6  || echo 'Cannot read libstdc++.so.6' \ ldd $(which mpirun)"
ls -l /g100_work/PROJECTS/spack/v0.17/prod/0.17.1/install/0.17/linux-centos8-skylake_avx512/gcc-8.4.1/gcc-10.2.0-cdzxiuliq73albrymyt5qhzzbto3oxga/lib64/libstdc++.so.6
md5sum /g100_work/PROJECTS/spack/v0.17/prod/0.17.1/install/0.17/linux-centos8-skylake_avx512/gcc-8.4.1/gcc-10.2.0-cdzxiuliq73albrymyt5qhzzbto3oxga/lib64/libstdc++.so.6 || echo "Cannot read libstdc++.so.6"
ldd $(which mpirun)
echo "check passed correctly..."



mpirun \
      -n 1 /g100_work/OGS23_PRACE_IT/csoto/eat/eat_env/bin/python3 run.py : \
      -n 148 /g100_work/OGS23_PRACE_IT/csoto/eat/eat_env/bin/eat-gotm --separate_restart_file --separate_gotm_yaml

date
